<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lettera [
<!ELEMENT lettera (cliente,ordine,responsabile)>
<!ELEMENT gentile (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>
<!ATTLIST ordine
  num CDATA #REQUERIDE>
<!ELEMENT la informiamo che i seguenti articoli da lei ordinati non sono piÃº disponibili a maggazino: (#PCDATA)>
<!ELEMENT ordine num="1234" (articolo+)>
<!ELEMENT articolo (codice,descr)
<!ELEMENT codice (#PCDATA)
<!ELEMENT descr (#PCDATA)
<!ATTLIST ordine
  ID  CDATA #REQUERIDE>
]>
<lettera>
  Gentile<cliente>tal dei tali</cliente>,
  <ordine num="_1234">
    <articolo>
      <codice>1</codice>
      <descr>articolo 1</descr>
    <articolo>
      <codice>5</codice>
      <descr>articolo 5</descr>
    </articolo>
  </ordine>
  cordiali saluti,
  <responsabile><tit>dr.</tit>Mario rosi</responsabile>
</lettera>
