<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partido [
<!ELEMENT equipos (equipo+)>
<!ELEMENT equipo(goles,minuto,amarilla,roja)>
  <!ELEMENT goles(#PCDATA)>
  <!ELEMENT minuto(#PCDATA)>
  <!ELEMENT amarilla(#PCDATA)>
  <!ELEMENT roja(#PCDATA)>
]>

 <partido>
  <equipos>
    <equipo>
      <goles>willy</goles>
      <minuto>13</minuto>
      <amarilla>willy</amarilla>
      <roja>fran</roja>
    </equipo>
    <equipo>
      <goles>manson</goles>
      <minuto>1</minuto>
      <amarilla>rocky</amarilla>
      <roja>fufu</roja>
    </equipo>
  </equipos>
 </partido>
